### ISSUE TITLE
Scala 2.13 support?

### ISSUE THREAD

**Issue by TJC** [lucidsoftware/akka-thread-context#3]
I wondered if there were any plans to update this to include Scala 2.13 support?

**Comment by tmccombs** [comment]
There are no definite plans. However, if you would like to submit a PR  adding 2.13 support, or even identify what doesn't work in 2.13 and needs to change, I'd be happy to look at it.

**Comment by TJC** [comment]
I've submitted a PR - #4

**Comment by tmccombs** [comment]
Fixed by #4
